export const branchData = [
  {
    id: 1,
    imageUrl: "https://picsum.photos/300/200?a",
    name: "Leexo",
    status: "false",
    address: "lorem ipLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's stan.",
    departments: 80,
    employees: 45,
  },
  {
    id: 2,
    imageUrl: "https://picsum.photos/300/200?b",
    name: "Skynoodle",
    status: "false",
    address: "Aseana 3, Aseana Ave. Diosdado Macapagal Blvd., Aseana City, Paranaque, 1701 Metro Manila (14th floor)",
    departments: 33,
    employees: 95,
  },
  {
    id: 3,
    imageUrl: "https://picsum.photos/300/200?c",
    name: "Eadel",
    status: "false",
    address: "2 Westerfield Hill",
    departments: 62,
    employees: 31,
  },
  {
    id: 4,
    imageUrl: "https://picsum.photos/300/200?d",
    name: "Quinu",
    status: "false",
    address: "052 Utah Trail",
    departments: 54,
    employees: 13,
  },
  {
    id: 5,
    imageUrl: "https://picsum.photos/300/200?e",
    name: "Feedfire",
    status: "false",
    address: "4133 Leroy Point",
    departments: 7,
    employees: 56,
  },
  {
    id: 6,
    imageUrl: "https://picsum.photos/300/200?f",
    name: "Trilith",
    status: "true",
    address: "02476 Saint Paul Center",
    departments: 58,
    employees: 71,
  },
  {
    id: 7,
    imageUrl: "https://picsum.photos/300/200?g",
    name: "Chatterbridge",
    status: "true",
    address: "3366 Sachtjen Way",
    departments: 21,
    employees: 70,
  },
  {
    id: 8,
    imageUrl: "https://picsum.photos/300/200?h",
    name: "Browsezoom",
    status: "true",
    address: "3 Crowley Street",
    departments: 56,
    employees: 46,
  },
  {
    id: 9,
    imageUrl: "https://picsum.photos/300/200?i",
    name: "Bubblemix",
    status: "true",
    address: "9 Chinook Road",
    departments: 20,
    employees: 59,
  },
  {
    id: 10,
    imageUrl: "https://picsum.photos/300/200?j",
    name: "Jaloo",
    status: "true",
    address: "082 Superior Court",
    departments: 47,
    employees: 23,
  },
  {
    id: 11,
    imageUrl: "https://picsum.photos/300/200?k",
    name: "Flipopia",
    status: "true",
    address: "6 Cardinal Junction",
    departments: 79,
    employees: 66,
  },
  {
    id: 12,
    imageUrl: "https://picsum.photos/300/200?l",
    name: "Devify",
    status: "false",
    address: "2 Rockefeller Alley",
    departments: 28,
    employees: 93,
  },
  {
    id: 13,
    imageUrl: "https://picsum.photos/300/200?m",
    name: "Wordware",
    status: "false",
    address: "94355 Commercial Drive",
    departments: 50,
    employees: 2,
  },
  {
    id: 14,
    imageUrl: "https://picsum.photos/300/200?n",
    name: "Topdrive",
    status: "true",
    address: "5385 Mockingbird Drive",
    departments: 42,
    employees: 76,
  },
  {
    id: 15,
    imageUrl: "https://picsum.photos/300/200?o",
    name: "Dabfeed",
    status: "true",
    address: "2 Knutson Park",
    departments: 29,
    employees: 88,
  },
  {
    id: 16,
    imageUrl: "https://picsum.photos/300/200?p",
    name: "Gevee",
    status: "false",
    address: "68 Stephen Center",
    departments: 47,
    employees: 37,
  },
  {
    id: 17,
    imageUrl: "https://picsum.photos/300/200?q",
    name: "Ainyx",
    status: "false",
    address: "08 Dorton Lane",
    departments: 92,
    employees: 82,
  },
  {
    id: 18,
    imageUrl: "https://picsum.photos/300/200?r",
    name: "Meejo",
    status: "true",
    address: "826 Morrow Point",
    departments: 14,
    employees: 21,
  },
  {
    id: 19,
    imageUrl: "https://picsum.photos/300/200?s",
    name: "Feedfire",
    status: "true",
    address: "315 Reindahl Junction",
    departments: 4,
    employees: 22,
  },
  {
    id: 20,
    imageUrl: "https://picsum.photos/300/200?t",
    name: "Tagchat",
    status: "true",
    address: "766 Lakeland Drive",
    departments: 49,
    employees: 46,
  },
  {
    id: 21,
    imageUrl: "https://picsum.photos/300/200?u",
    name: "Photobug",
    status: "false",
    address: "75 Arrowood Center",
    departments: 81,
    employees: 44,
  },
  {
    id: 22,
    imageUrl: "https://picsum.photos/300/200?v",
    name: "Dabvine",
    status: "false",
    address: "181 Westend Crossing",
    departments: 46,
    employees: 94,
  },
  {
    id: 23,
    imageUrl: "https://picsum.photos/300/200?w",
    name: "Livepath",
    status: "true",
    address: "6 Hoepker Junction",
    departments: 39,
    employees: 75,
  },
  {
    id: 24,
    imageUrl: "https://picsum.photos/300/200?x",
    name: "Thoughtstorm",
    status: "true",
    address: "440 Crescent Oaks Park",
    departments: 46,
    employees: 100,
  },
  {
    id: 25,
    imageUrl: "https://picsum.photos/300/200?y",
    name: "Twimbo",
    status: "false",
    address: "01581 Sutherland Court",
    departments: 96,
    employees: 18,
  },
  {
    id: 26,
    imageUrl: "https://picsum.photos/300/200?z",
    name: "LiveZ",
    status: "true",
    address: "39 Jackson Circle",
    departments: 4,
    employees: 25,
  },
  {
    id: 1,
    imageUrl: "https://picsum.photos/300/200?a",
    name: "Leexo",
    status: "false",
    address: "lorem ipLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's stan.",
    departments: 80,
    employees: 45,
    
  },
  {
    id: 1,
    imageUrl: "https://picsum.photos/300/200?a",
    name: "Leexo",
    status: "false",
    address: "lorem ipLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's stan.",
    departments: 80,
    employees: 45,
  },
  {
    id: 1,
    imageUrl: "https://picsum.photos/300/200?a",
    name: "Leexo",
    status: "false",
    address: "lorem ipLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's stan.",
    departments: 80,
    employees: 45,
  },
  {
    id: 1,
    imageUrl: "https://picsum.photos/300/200?a",
    name: "Leexo",
    status: "false",
    address: "lorem ipLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's stan.",
    departments: 80,
    employees: 45,
  },
  {
    id: 1,
    imageUrl: "https://picsum.photos/300/200?a",
    name: "Leexo",
    status: "false",
    address: "lorem ipLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's stan.",
    departments: 80,
    employees: 45,
  },
  {
    id: 1,
    imageUrl: "https://picsum.photos/300/200?a",
    name: "Leexo",
    status: "false",
    address: "lorem ipLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's stan.",
    departments: 80,
    employees: 45,
  },
  {
    id: 1,
    imageUrl: "https://picsum.photos/300/200?a",
    name: "Leexo",
    status: "false",
    address: "lorem ipLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's stan.",
    departments: 80,
    employees: 45,
  },
  {
    id: 1,
    imageUrl: "https://picsum.photos/300/200?a",
    name: "Leexo",
    status: "false",
    address: "lorem ipLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's stan.",
    departments: 80,
    employees: 45,
  },
];
