export const fake = [
    {
        id: 1,
        name: "Accounting",
        status: 'true',
        branch: "verykool",
        departmentHead: "Bertha Gregoretti",
        position: "Dental Hygienist",
        contactDetails: "bgregoretti0@hugedomains.com",
        number: '09278787878',
        positions: 45,
        employees: 76
      },
      {
        id: 2,
        name: "Support",
        status: 'true',
        branch: "alcatel",
        departmentHead: "Blanch Caygill",
        position: "Assistant Professor",
        contactDetails: "bcaygill1@i2i.jp",
        number: '09278787878',
        positions: 15,
        employees: 74
      },
      {
        id: 3,
        name: "Services",
        status: 'false',
        branch: "Bird",
        departmentHead: "Kleon Duignan",
        position: "Senior Editor",
        contactDetails: "kduignan2@purevolume.com",
        number: '09278787878',
        positions: 69,
        employees: 57
      },
      {
        id: 4,
        name: "Training",
        status: 'false',
        branch: "Panasonic",
        departmentHead: "Helena Orpin",
        position: "Statistician I",
        contactDetails: "horpin3@example.com",
        number: '09278787878',
        positions: 57,
        employees: 88
      },
      {
        id: 5,
        name: "Marketing",
        status: 'false',
        branch: "alcatel",
        departmentHead: "Brianna Swaffer",
        position: "Professor",
        contactDetails: "bswaffer4@sciencedirect.com",
        number: '09278787878',
        positions: 2,
        employees: 41
      },
      {
        id: 6,
        name: "Marketing",
        status: 'true',
        branch: "verykool",
        departmentHead: "Kaia Braim",
        position: "Computer Systems Analyst I",
        contactDetails: "kbraim5@mashable.com",
        number: '09278787878',
        positions: 31,
        employees: 18
      },
      {
        id: 7,
        name: "Services",
        status: 'false',
        branch: "Samsung",
        departmentHead: "Leland Hefferan",
        position: "Paralegal",
        contactDetails: "lhefferan6@cnet.com",
        number: '09278787878',
        positions: 33,
        employees: 77
      },
      {
        id: 8,
        name: "Engineering",
        status: 'false',
        branch: "Motorola",
        departmentHead: "Rena Edards",
        position: "Operator",
        contactDetails: "redards7@ask.com",
        number: '09278787878',
        positions: 14,
        employees: 91
      },
      {
        id: 9,
        name: "Research and Development",
        status: 'false',
        branch: "Panasonic",
        departmentHead: "Zak Slimming",
        position: "Food Chemist",
        contactDetails: "zslimming8@wix.com",
        number: '09278787878',
        positions: 13,
        employees: 100
      },
      {
        id: 10,
        name: "Product Management",
        status: 'false',
        branch: "ZTE",
        departmentHead: "Bartholomeus Leggat",
        position: "Human Resources Assistant IV",
        contactDetails: "bleggat9@bing.com",
        number: '09278787878',
        positions: 49,
        employees: 1
      },
      {
        id: 11,
        name: "Research and Development",
        status: 'true',
        branch: "Honor",
        departmentHead: "Theodor MacCurley",
        position: "Graphic Designer",
        contactDetails: "tmaccurleya@upenn.edu",
        number: '09278787878',
        positions: 13,
        employees: 89
      },
      {
        id: 12,
        name: "Product Management",
        status: 'true',
        branch: "Samsung",
        departmentHead: "Thadeus Lonergan",
        position: "Human Resources Manager",
        contactDetails: "tlonerganb@360.cn",
        number: '09278787878',
        positions: 75,
        employees: 71
      },
      {
        id: 13,
        name: "Business Development",
        status: 'true',
        branch: "Xiaomi",
        departmentHead: "Eleen Fontanet",
        position: "Clinical Specialist",
        contactDetails: "efontanetc@census.gov",
        number: '09278787878',
        positions: 92,
        employees: 70
      },
      {
        id: 14,
        name: "Services",
        status: 'false',
        branch: "Samsung",
        departmentHead: "Bret Undrell",
        position: "Actuary",
        contactDetails: "bundrelld@salon.com",
        number: '09278787878',
        positions: 63,
        employees: 42
      },
      {
        id: 15,
        name: "Services",
        status: 'true',
        branch: "Spice",
        departmentHead: "Madlen Alywen",
        position: "Software Engineer II",
        contactDetails: "malywene@php.net",
        number: '09278787878',
        positions: 33,
        employees: 13
      },
      {
        id: 16,
        name: "Legal",
        status: 'true',
        branch: "Meizu",
        departmentHead: "Nonna Wilstead",
        position: "Operator",
        contactDetails: "nwilsteadf@go.com",
        number: '09278787878',
        positions: 98,
        employees: 60
      },
      {
        id: 17,
        name: "Business Development",
        status: 'false',
        branch: "i-mobile",
        departmentHead: "Hazlett Giannasi",
        position: "Recruiting Manager",
        contactDetails: "hgiannasig@alibaba.com",
        number: '09278787878',
        positions: 62,
        employees: 29
      },
      {
        id: 18,
        name: "Support",
        status: 'false',
        branch: "LG",
        departmentHead: "Carmen Cassam",
        position: "Structural Analysis Engineer",
        contactDetails: "ccassamh@mapy.cz",
        number: '09278787878',
        positions: 75,
        employees: 41
      },
      {
        id: 19,
        name: "Sales",
        status: 'true',
        branch: "BlackBerry",
        departmentHead: "Gabriela Garforth",
        position: "Analog Circuit Design manager",
        contactDetails: "ggarforthi@ihg.com",
        number: '09278787878',
        positions: 38,
        employees: 54
      },
      {
        id: 20,
        name: "Legal",
        status: 'true',
        branch: "Philips",
        departmentHead: "Dorthea Staples",
        position: "VP Marketing",
        contactDetails: "dstaplesj@miitbeian.gov.cn",
        number: '09278787878',
        positions: 59,
        employees: 51
      }
];
